import voiceover from "./voiceover.json";

export const lessonData = {
  title: "密码判断",
  steps: ["题面", "样例", "思路", "流程", "代码", "总结"],
  problem: {
    title: "密码判断",
    meta: ["难度：语法入门", "输入：多行密码", "输出：密码正确，欢迎您！"],
    description: "编写一段能够实现密码判断功能的代码。",
    requirements: [
      "程序运行开始后，用户通过键盘输入密码，格式为字符串。",
      "如果密码错误，让用户继续输入密码。",
      "如果密码正确，屏幕输出“密码正确，欢迎您！”，并终止循环，结束程序。",
      "正确的密码可以在程序中明确，无需用户输入。",
    ],
    sampleInput: ["1", "12", "123", "1234", "12345", "123456"],
    sampleOutput: ["密码正确，欢迎您！"],
    hint: "input() 输入函数的括号中不允许添加任何信息。",
    sourceNote: "题面页根据用户提供截图重建，非官方原图。",
  },
  intro: {
    ruleCards: [
      { title: "密码是字符串", text: "每次 input() 读到的内容都是一串字符。" },
      { title: "密码可写死", text: "正确密码直接在程序里明确，例如 123456。" },
      { title: "错了继续输入", text: "输入不相等时不输出，回到循环开头。" },
      { title: "对了立刻退出", text: "输出欢迎语后用 break 结束循环。" },
    ],
    inputLines: ["多行密码", "直到出现正确密码"],
    outputLines: ["只在密码正确时输出一行", "错误密码不输出提示"],
    tags: ["Python", "语法入门", "while 循环", "字符串比较"],
    caption: voiceover.intro.text,
  },
  sample: {
    password: "123456",
    input: ["1", "12", "123", "1234", "12345", "123456"],
    output: ["密码正确，欢迎您！"],
    rows: [
      { value: "1", compare: "1 == 123456", status: "错误", action: "继续循环", result: "无输出" },
      { value: "12", compare: "12 == 123456", status: "错误", action: "继续循环", result: "无输出" },
      { value: "123", compare: "123 == 123456", status: "错误", action: "继续循环", result: "无输出" },
      { value: "1234", compare: "1234 == 123456", status: "错误", action: "继续循环", result: "无输出" },
      { value: "12345", compare: "12345 == 123456", status: "错误", action: "继续循环", result: "无输出" },
      { value: "123456", compare: "123456 == 123456", status: "正确", action: "输出并退出", result: "密码正确，欢迎您！" },
    ],
    caption: voiceover.sample.text,
  },
  strategy: {
    tasks: [
      "先设定正确密码 password",
      "用 while True 持续等待输入",
      "每轮只写 input()，括号里不加提示文字",
      "判断 s == password",
      "正确时 print，再 break",
      "错误时什么都不做，自然进入下一轮",
    ],
    pseudoLines: [
      "password = \"123456\"",
      "一直循环:",
      "    s = input()",
      "    如果 s 等于 password:",
      "        输出欢迎语",
      "        跳出循环",
    ],
    warning: "题目要求错误时继续输入，不要求也不允许输出“密码错误”。",
    caption: voiceover.strategy.text,
  },
  trace: {
    columns: ["轮次", "输入 s", "比较结果", "程序动作"],
    rows: [
      ["1", "\"1\"", "False", "回到循环开头"],
      ["2", "\"12\"", "False", "回到循环开头"],
      ["3", "\"123\"", "False", "回到循环开头"],
      ["4", "\"1234\"", "False", "回到循环开头"],
      ["5", "\"12345\"", "False", "回到循环开头"],
      ["6", "\"123456\"", "True", "输出并 break"],
    ],
    formula: "s == password",
    caption: voiceover.trace.text,
  },
  code: {
    lines: [
      "password = \"123456\"",
      "",
      "while True:",
      "    s = input()",
      "    if s == password:",
      "        print(\"密码正确，欢迎您！\")",
      "        break",
    ],
    highlight: [1, 3, 4, 5, 6, 7],
    callouts: [
      { title: "固定正确密码", text: "题目允许在程序中明确正确密码。" },
      { title: "持续输入", text: "不知道用户会错几次，所以用 while True。" },
      { title: "input() 不加提示", text: "OJ 比对输出，提示文字会导致答案错误。" },
      { title: "break 结束", text: "密码正确后必须终止循环，否则程序会继续等待输入。" },
    ],
    caption: voiceover.code.text,
  },
  summary: {
    chain: ["设定 password", "读入 s", "比较 s == password", "正确输出", "break 结束"],
    mistakes: [
      "input(\"请输入密码\") 在 OJ 中会多输出提示文字",
      "错误时 print(\"密码错误\")，会产生题目没要求的输出",
      "把密码写成数字 123456，再和字符串输入比较",
      "输出正确后忘记 break，循环不会结束",
    ],
    keyCode: "if s == password:",
    caption: voiceover.summary.text,
  },
};
